name: Daily PV forecast

on:
  schedule:
    # GitHub Actions cron je v UTC.
    # Europe/Prague = 8:00 je v zimě 7:00 UTC, v létě 6:00 UTC.
    # Nejjednodušší robustní řešení: spustit v 6:00 i 7:00 UTC a skript pustit jen když je lokálně 8:00.
    - cron: "0 6 * * *"
    - cron: "0 7 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  forecast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run forecast (only at 08:00 Europe/Prague)
        env:
          TZ: Europe/Prague
        run: |
          H=$(date +%H)
          M=$(date +%M)
          echo "Local time (Prague): $(date)"
          if [ "$H" != "08" ] || [ "$M" != "00" ]; then
            echo "Not 08:00 in Europe/Prague, skipping."
            exit 0
          fi
          python -u pv_forecast.py

      - name: Commit forecast summary
        run: |
          if [ -f forecasts/forecast_daily_summary.csv ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add forecasts/forecast_daily_summary.csv
            git commit -m "Update daily forecast summary" || echo "No changes to commit"
            git push
          else
            echo "No summary file found, nothing to commit."
          fi
